# Generated by Django 5.2.8 on 2025-12-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_gender_alter_profile_phone_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promotional_emails',
            field=models.BooleanField(default=False),
        ),
    ]
